### ISSUE TITLE
Problems installing requests-negotiate 1.3.1

### ISSUE THREAD

**Issue by postrational** [ox-it/requests-negotiate#2]
Hello there,

When I try to install the new version of requests-negotiate, I am running into the following problem:

    $ pip install --no-cache-dir requests-negotiate
    Collecting requests-negotiate
      Downloading requests-negotiate-1.3.1.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/var/folders/85/s9mmc1ln0r95fhwqy5x1r9nw0000gp/T/pip-build-vgnqxwmb/requests-negotiate/setup.py", line 12, in <module>
            long_description=open('README.md').read(),
        FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/85/s9mmc1ln0r95fhwqy5x1r9nw0000gp/T/pip-build-vgnqxwmb/requests-negotiate/

    $ python --version
    Python 3.4.2

    $ pip --version
    pip 8.1.2
    

Previous version (1.3) still works fine.

**Comment by alexsdutton** [comment]
Sorry! Give me a moment and I'll release a new version

**Comment by alexsdutton** [comment]
@postrational I've just uploaded 1.3.2 to PyPI. Could you double-check that it works?

Also, did you spot that this library has moved from python-gssapi to gssapi?

**Comment by postrational** [comment]
Hello again, version 1.3.2 fixed the problem listed above, but we're running into another issue:

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-olgb4iir/requests-negotiate/setup.py", line 12, in <module>
    long_description=open('README.md').read(),
    File "/opt/path/to/venv/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 515: ordinal not in range(128)

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-olgb4iir/requests-negotiate/

I believe that the long dash characters (—) in the readme are to blame. I prepared a pull request (#3) which addresses this.

**Comment by postrational** [comment]
OK, all is well again. Thanks for your quick reaction.
